site_name: Alectrion

repo_name: "2023-1-Alectrion"
repo_url: "https://github.com/fga-eps-mds/2023-1-Alectrion-DOC"

theme:
  name: material
  language: "pt"
  features: navigation.tabs
  logo: assets/logos/alectrionLogo.svg
  favicon: assets/logos/alectrionLogo.svg
  palette:
    primary: "orange"
    accent: "black"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Plano e monitoramento:
    - Plano de comunicação: plano-comunicacao.md
    - Plano de custos: plano-custos.md
    - Análise de riscos: plano-riscos.md
  - Contribuição:
    - Guia de Contribuição: documentacao/guiaDeContribuicao.md
    - Código de Conduta: documentacao/codigo-conduta.md
    - Guia de Estilo: documentacao/guia-de-estilo.md
    - Termo de abertura: documentacao/tap.md
  - Protótipo: documentacao/prototipo.md
  - Semanas e Sprints: semanas-sprints.md

dev_addr: "0.0.0.0:8000"
