site_name: Alectrion

repo_name: "2023-1-Alectrion"
repo_url: "https://github.com/fga-eps-mds/2023-1-Alectrion-DOC"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  language: "pt"
  features: navigation.tabs
  logo: assets/logos/alectrionLogo.svg
  favicon: assets/logos/alectrionLogo.svg
  palette:
    primary: "orange"
    accent: "black"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Plano e monitoramento:
    - Plano de comunicação: plano-comunicacao.md
    - Plano de custos: plano-custos.md
<<<<<<< HEAD
    - Plano de qualidade: plano-qualidade.md
=======
    - EVM Agile: evm.md
>>>>>>> 12bf626 (#38 docs: adicionando evm)
    - Análise de riscos: plano-riscos.md
  - Contribuição:
    - Guia de contribuição: documentacao/guiaDeContribuicao.md
    - Código de conduta: documentacao/codigo-conduta.md
  - Organização do projeto:
    - Metodologias: metodologias.md
    - Termo de abertura: documentacao/tap.md
    - Estrutura analítica do projeto: documentacao/eap.md
    - Documento de arquitetura: documentacao/arquitetura.md
  - Protótipo: 
    - Protótipo de alta fidelidade: documentacao/prototipo.md
    - Guia de estilo: documentacao/guia-de-estilo.md
  - Semanas e Sprints: semanas-sprints.md
<<<<<<< HEAD
  - Lean Inception:
    - Visão do Produto: documentacao/lean-inception/visao-do-produto.md
    - É, Não é, Faz, Não faz: documentacao/lean-inception/e-nao-e.md
    - Objetivos do Produto: documentacao/lean-inception/objetivos.md
    - Personas: documentacao/lean-inception/personas.md
    - Jornadas de Usuário: documentacao/lean-inception/jornadas.md
    - Brainstorm de Funcionalidades: documentacao/lean-inception/brainstorm.md
    - Revisão técnica, de negócio e de UX: documentacao/lean-inception/revisao.md
    - Sequenciador: documentacao/lean-inception/sequenciador.md
    - Canvas MVP: documentacao/lean-inception/canvas.md
    - Backlog inicial do produto: documentacao/backlog.md
=======

>>>>>>> 12bf626 (#38 docs: adicionando evm)

dev_addr: "0.0.0.0:8000"
